#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn07_11.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAn07-11")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANGGIADAT(BANGGIADAT instance);
    partial void UpdateBANGGIADAT(BANGGIADAT instance);
    partial void DeleteBANGGIADAT(BANGGIADAT instance);
    partial void InsertTINHTHANH(TINHTHANH instance);
    partial void UpdateTINHTHANH(TINHTHANH instance);
    partial void DeleteTINHTHANH(TINHTHANH instance);
    partial void InsertQUANHUYEN(QUANHUYEN instance);
    partial void UpdateQUANHUYEN(QUANHUYEN instance);
    partial void DeleteQUANHUYEN(QUANHUYEN instance);
    partial void InsertLOAIHINH(LOAIHINH instance);
    partial void UpdateLOAIHINH(LOAIHINH instance);
    partial void DeleteLOAIHINH(LOAIHINH instance);
    partial void InsertCHITIETLOAI(CHITIETLOAI instance);
    partial void UpdateCHITIETLOAI(CHITIETLOAI instance);
    partial void DeleteCHITIETLOAI(CHITIETLOAI instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DoAn07_11ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANGGIADAT> BANGGIADATs
		{
			get
			{
				return this.GetTable<BANGGIADAT>();
			}
		}
		
		public System.Data.Linq.Table<TINHTHANH> TINHTHANHs
		{
			get
			{
				return this.GetTable<TINHTHANH>();
			}
		}
		
		public System.Data.Linq.Table<QUANHUYEN> QUANHUYENs
		{
			get
			{
				return this.GetTable<QUANHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<LOAIHINH> LOAIHINHs
		{
			get
			{
				return this.GetTable<LOAIHINH>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETLOAI> CHITIETLOAIs
		{
			get
			{
				return this.GetTable<CHITIETLOAI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGGIADAT")]
	public partial class BANGGIADAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BANGGIADAT;
		
		private System.Nullable<int> _ID_QUANHUYEN;
		
		private string _TENDUONG;
		
		private string _DOANTU;
		
		private System.Nullable<int> _VT1;
		
		private System.Nullable<int> _VT2;
		
		private System.Nullable<int> _VT3;
		
		private System.Nullable<int> _VT4;
		
		private System.Nullable<int> _VT5;
		
		private System.Nullable<int> _ID_LOAIHINH;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<System.DateTime> _NGAYSUA;
		
		private System.Nullable<int> _NGUOITAO;
		
		private System.Nullable<int> _NGUOISUA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private System.Nullable<int> _ID_CHITIETLOAI;
		
		private EntityRef<QUANHUYEN> _QUANHUYEN;
		
		private EntityRef<LOAIHINH> _LOAIHINH;
		
		private EntityRef<CHITIETLOAI> _CHITIETLOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BANGGIADATChanging(int value);
    partial void OnID_BANGGIADATChanged();
    partial void OnID_QUANHUYENChanging(System.Nullable<int> value);
    partial void OnID_QUANHUYENChanged();
    partial void OnTENDUONGChanging(string value);
    partial void OnTENDUONGChanged();
    partial void OnDOANTUChanging(string value);
    partial void OnDOANTUChanged();
    partial void OnVT1Changing(System.Nullable<int> value);
    partial void OnVT1Changed();
    partial void OnVT2Changing(System.Nullable<int> value);
    partial void OnVT2Changed();
    partial void OnVT3Changing(System.Nullable<int> value);
    partial void OnVT3Changed();
    partial void OnVT4Changing(System.Nullable<int> value);
    partial void OnVT4Changed();
    partial void OnVT5Changing(System.Nullable<int> value);
    partial void OnVT5Changed();
    partial void OnID_LOAIHINHChanging(System.Nullable<int> value);
    partial void OnID_LOAIHINHChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnNGAYSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUAChanged();
    partial void OnNGUOITAOChanging(System.Nullable<int> value);
    partial void OnNGUOITAOChanged();
    partial void OnNGUOISUAChanging(System.Nullable<int> value);
    partial void OnNGUOISUAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnID_CHITIETLOAIChanging(System.Nullable<int> value);
    partial void OnID_CHITIETLOAIChanged();
    #endregion
		
		public BANGGIADAT()
		{
			this._QUANHUYEN = default(EntityRef<QUANHUYEN>);
			this._LOAIHINH = default(EntityRef<LOAIHINH>);
			this._CHITIETLOAI = default(EntityRef<CHITIETLOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BANGGIADAT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BANGGIADAT
		{
			get
			{
				return this._ID_BANGGIADAT;
			}
			set
			{
				if ((this._ID_BANGGIADAT != value))
				{
					this.OnID_BANGGIADATChanging(value);
					this.SendPropertyChanging();
					this._ID_BANGGIADAT = value;
					this.SendPropertyChanged("ID_BANGGIADAT");
					this.OnID_BANGGIADATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUANHUYEN", DbType="Int")]
		public System.Nullable<int> ID_QUANHUYEN
		{
			get
			{
				return this._ID_QUANHUYEN;
			}
			set
			{
				if ((this._ID_QUANHUYEN != value))
				{
					if (this._QUANHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_QUANHUYENChanging(value);
					this.SendPropertyChanging();
					this._ID_QUANHUYEN = value;
					this.SendPropertyChanged("ID_QUANHUYEN");
					this.OnID_QUANHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(250)")]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this.OnTENDUONGChanging(value);
					this.SendPropertyChanging();
					this._TENDUONG = value;
					this.SendPropertyChanged("TENDUONG");
					this.OnTENDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOANTU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DOANTU
		{
			get
			{
				return this._DOANTU;
			}
			set
			{
				if ((this._DOANTU != value))
				{
					this.OnDOANTUChanging(value);
					this.SendPropertyChanging();
					this._DOANTU = value;
					this.SendPropertyChanged("DOANTU");
					this.OnDOANTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VT1", DbType="Int")]
		public System.Nullable<int> VT1
		{
			get
			{
				return this._VT1;
			}
			set
			{
				if ((this._VT1 != value))
				{
					this.OnVT1Changing(value);
					this.SendPropertyChanging();
					this._VT1 = value;
					this.SendPropertyChanged("VT1");
					this.OnVT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VT2", DbType="Int")]
		public System.Nullable<int> VT2
		{
			get
			{
				return this._VT2;
			}
			set
			{
				if ((this._VT2 != value))
				{
					this.OnVT2Changing(value);
					this.SendPropertyChanging();
					this._VT2 = value;
					this.SendPropertyChanged("VT2");
					this.OnVT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VT3", DbType="Int")]
		public System.Nullable<int> VT3
		{
			get
			{
				return this._VT3;
			}
			set
			{
				if ((this._VT3 != value))
				{
					this.OnVT3Changing(value);
					this.SendPropertyChanging();
					this._VT3 = value;
					this.SendPropertyChanged("VT3");
					this.OnVT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VT4", DbType="Int")]
		public System.Nullable<int> VT4
		{
			get
			{
				return this._VT4;
			}
			set
			{
				if ((this._VT4 != value))
				{
					this.OnVT4Changing(value);
					this.SendPropertyChanging();
					this._VT4 = value;
					this.SendPropertyChanged("VT4");
					this.OnVT4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VT5", DbType="Int")]
		public System.Nullable<int> VT5
		{
			get
			{
				return this._VT5;
			}
			set
			{
				if ((this._VT5 != value))
				{
					this.OnVT5Changing(value);
					this.SendPropertyChanging();
					this._VT5 = value;
					this.SendPropertyChanged("VT5");
					this.OnVT5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIHINH", DbType="Int")]
		public System.Nullable<int> ID_LOAIHINH
		{
			get
			{
				return this._ID_LOAIHINH;
			}
			set
			{
				if ((this._ID_LOAIHINH != value))
				{
					if (this._LOAIHINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIHINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIHINH = value;
					this.SendPropertyChanged("ID_LOAIHINH");
					this.OnID_LOAIHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSUA
		{
			get
			{
				return this._NGAYSUA;
			}
			set
			{
				if ((this._NGAYSUA != value))
				{
					this.OnNGAYSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUA = value;
					this.SendPropertyChanged("NGAYSUA");
					this.OnNGAYSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAO", DbType="Int")]
		public System.Nullable<int> NGUOITAO
		{
			get
			{
				return this._NGUOITAO;
			}
			set
			{
				if ((this._NGUOITAO != value))
				{
					this.OnNGUOITAOChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAO = value;
					this.SendPropertyChanged("NGUOITAO");
					this.OnNGUOITAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOISUA", DbType="Int")]
		public System.Nullable<int> NGUOISUA
		{
			get
			{
				return this._NGUOISUA;
			}
			set
			{
				if ((this._NGUOISUA != value))
				{
					this.OnNGUOISUAChanging(value);
					this.SendPropertyChanging();
					this._NGUOISUA = value;
					this.SendPropertyChanged("NGUOISUA");
					this.OnNGUOISUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHITIETLOAI", DbType="Int")]
		public System.Nullable<int> ID_CHITIETLOAI
		{
			get
			{
				return this._ID_CHITIETLOAI;
			}
			set
			{
				if ((this._ID_CHITIETLOAI != value))
				{
					if (this._CHITIETLOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CHITIETLOAIChanging(value);
					this.SendPropertyChanging();
					this._ID_CHITIETLOAI = value;
					this.SendPropertyChanged("ID_CHITIETLOAI");
					this.OnID_CHITIETLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANHUYEN_BANGGIADAT", Storage="_QUANHUYEN", ThisKey="ID_QUANHUYEN", OtherKey="ID_QUANHUYEN", IsForeignKey=true)]
		public QUANHUYEN QUANHUYEN
		{
			get
			{
				return this._QUANHUYEN.Entity;
			}
			set
			{
				QUANHUYEN previousValue = this._QUANHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._QUANHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUANHUYEN.Entity = null;
						previousValue.BANGGIADATs.Remove(this);
					}
					this._QUANHUYEN.Entity = value;
					if ((value != null))
					{
						value.BANGGIADATs.Add(this);
						this._ID_QUANHUYEN = value.ID_QUANHUYEN;
					}
					else
					{
						this._ID_QUANHUYEN = default(Nullable<int>);
					}
					this.SendPropertyChanged("QUANHUYEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINH_BANGGIADAT", Storage="_LOAIHINH", ThisKey="ID_LOAIHINH", OtherKey="ID_LOAIHINH", IsForeignKey=true)]
		public LOAIHINH LOAIHINH
		{
			get
			{
				return this._LOAIHINH.Entity;
			}
			set
			{
				LOAIHINH previousValue = this._LOAIHINH.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHINH.Entity = null;
						previousValue.BANGGIADATs.Remove(this);
					}
					this._LOAIHINH.Entity = value;
					if ((value != null))
					{
						value.BANGGIADATs.Add(this);
						this._ID_LOAIHINH = value.ID_LOAIHINH;
					}
					else
					{
						this._ID_LOAIHINH = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIHINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETLOAI_BANGGIADAT", Storage="_CHITIETLOAI", ThisKey="ID_CHITIETLOAI", OtherKey="ID_CHITIETLOAI", IsForeignKey=true)]
		public CHITIETLOAI CHITIETLOAI
		{
			get
			{
				return this._CHITIETLOAI.Entity;
			}
			set
			{
				CHITIETLOAI previousValue = this._CHITIETLOAI.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETLOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETLOAI.Entity = null;
						previousValue.BANGGIADATs.Remove(this);
					}
					this._CHITIETLOAI.Entity = value;
					if ((value != null))
					{
						value.BANGGIADATs.Add(this);
						this._ID_CHITIETLOAI = value.ID_CHITIETLOAI;
					}
					else
					{
						this._ID_CHITIETLOAI = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHITIETLOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTHANH")]
	public partial class TINHTHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TINHTHANH;
		
		private string _TEN;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<System.DateTime> _NGAYSUA;
		
		private System.Nullable<int> _NGUOITAO;
		
		private System.Nullable<int> _NGUOISUA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntitySet<QUANHUYEN> _QUANHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TINHTHANHChanging(int value);
    partial void OnID_TINHTHANHChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnNGAYSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUAChanged();
    partial void OnNGUOITAOChanging(System.Nullable<int> value);
    partial void OnNGUOITAOChanged();
    partial void OnNGUOISUAChanging(System.Nullable<int> value);
    partial void OnNGUOISUAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public TINHTHANH()
		{
			this._QUANHUYENs = new EntitySet<QUANHUYEN>(new Action<QUANHUYEN>(this.attach_QUANHUYENs), new Action<QUANHUYEN>(this.detach_QUANHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TINHTHANH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TINHTHANH
		{
			get
			{
				return this._ID_TINHTHANH;
			}
			set
			{
				if ((this._ID_TINHTHANH != value))
				{
					this.OnID_TINHTHANHChanging(value);
					this.SendPropertyChanging();
					this._ID_TINHTHANH = value;
					this.SendPropertyChanged("ID_TINHTHANH");
					this.OnID_TINHTHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(250)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSUA
		{
			get
			{
				return this._NGAYSUA;
			}
			set
			{
				if ((this._NGAYSUA != value))
				{
					this.OnNGAYSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUA = value;
					this.SendPropertyChanged("NGAYSUA");
					this.OnNGAYSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAO", DbType="Int")]
		public System.Nullable<int> NGUOITAO
		{
			get
			{
				return this._NGUOITAO;
			}
			set
			{
				if ((this._NGUOITAO != value))
				{
					this.OnNGUOITAOChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAO = value;
					this.SendPropertyChanged("NGUOITAO");
					this.OnNGUOITAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOISUA", DbType="Int")]
		public System.Nullable<int> NGUOISUA
		{
			get
			{
				return this._NGUOISUA;
			}
			set
			{
				if ((this._NGUOISUA != value))
				{
					this.OnNGUOISUAChanging(value);
					this.SendPropertyChanging();
					this._NGUOISUA = value;
					this.SendPropertyChanged("NGUOISUA");
					this.OnNGUOISUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANH_QUANHUYEN", Storage="_QUANHUYENs", ThisKey="ID_TINHTHANH", OtherKey="ID_TINHTHANH")]
		public EntitySet<QUANHUYEN> QUANHUYENs
		{
			get
			{
				return this._QUANHUYENs;
			}
			set
			{
				this._QUANHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QUANHUYENs(QUANHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANH = this;
		}
		
		private void detach_QUANHUYENs(QUANHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANHUYEN")]
	public partial class QUANHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_QUANHUYEN;
		
		private int _ID_TINHTHANH;
		
		private string _TEN;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<System.DateTime> _NGAYSUA;
		
		private System.Nullable<int> _NGUOITAO;
		
		private System.Nullable<int> _NGUOISUA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntitySet<BANGGIADAT> _BANGGIADATs;
		
		private EntityRef<TINHTHANH> _TINHTHANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_QUANHUYENChanging(int value);
    partial void OnID_QUANHUYENChanged();
    partial void OnID_TINHTHANHChanging(int value);
    partial void OnID_TINHTHANHChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnNGAYSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUAChanged();
    partial void OnNGUOITAOChanging(System.Nullable<int> value);
    partial void OnNGUOITAOChanged();
    partial void OnNGUOISUAChanging(System.Nullable<int> value);
    partial void OnNGUOISUAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public QUANHUYEN()
		{
			this._BANGGIADATs = new EntitySet<BANGGIADAT>(new Action<BANGGIADAT>(this.attach_BANGGIADATs), new Action<BANGGIADAT>(this.detach_BANGGIADATs));
			this._TINHTHANH = default(EntityRef<TINHTHANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUANHUYEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_QUANHUYEN
		{
			get
			{
				return this._ID_QUANHUYEN;
			}
			set
			{
				if ((this._ID_QUANHUYEN != value))
				{
					this.OnID_QUANHUYENChanging(value);
					this.SendPropertyChanging();
					this._ID_QUANHUYEN = value;
					this.SendPropertyChanged("ID_QUANHUYEN");
					this.OnID_QUANHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TINHTHANH", DbType="Int NOT NULL")]
		public int ID_TINHTHANH
		{
			get
			{
				return this._ID_TINHTHANH;
			}
			set
			{
				if ((this._ID_TINHTHANH != value))
				{
					if (this._TINHTHANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TINHTHANHChanging(value);
					this.SendPropertyChanging();
					this._ID_TINHTHANH = value;
					this.SendPropertyChanged("ID_TINHTHANH");
					this.OnID_TINHTHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(250)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSUA
		{
			get
			{
				return this._NGAYSUA;
			}
			set
			{
				if ((this._NGAYSUA != value))
				{
					this.OnNGAYSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUA = value;
					this.SendPropertyChanged("NGAYSUA");
					this.OnNGAYSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAO", DbType="Int")]
		public System.Nullable<int> NGUOITAO
		{
			get
			{
				return this._NGUOITAO;
			}
			set
			{
				if ((this._NGUOITAO != value))
				{
					this.OnNGUOITAOChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAO = value;
					this.SendPropertyChanged("NGUOITAO");
					this.OnNGUOITAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOISUA", DbType="Int")]
		public System.Nullable<int> NGUOISUA
		{
			get
			{
				return this._NGUOISUA;
			}
			set
			{
				if ((this._NGUOISUA != value))
				{
					this.OnNGUOISUAChanging(value);
					this.SendPropertyChanging();
					this._NGUOISUA = value;
					this.SendPropertyChanged("NGUOISUA");
					this.OnNGUOISUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUANHUYEN_BANGGIADAT", Storage="_BANGGIADATs", ThisKey="ID_QUANHUYEN", OtherKey="ID_QUANHUYEN")]
		public EntitySet<BANGGIADAT> BANGGIADATs
		{
			get
			{
				return this._BANGGIADATs;
			}
			set
			{
				this._BANGGIADATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANH_QUANHUYEN", Storage="_TINHTHANH", ThisKey="ID_TINHTHANH", OtherKey="ID_TINHTHANH", IsForeignKey=true)]
		public TINHTHANH TINHTHANH
		{
			get
			{
				return this._TINHTHANH.Entity;
			}
			set
			{
				TINHTHANH previousValue = this._TINHTHANH.Entity;
				if (((previousValue != value) 
							|| (this._TINHTHANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTHANH.Entity = null;
						previousValue.QUANHUYENs.Remove(this);
					}
					this._TINHTHANH.Entity = value;
					if ((value != null))
					{
						value.QUANHUYENs.Add(this);
						this._ID_TINHTHANH = value.ID_TINHTHANH;
					}
					else
					{
						this._ID_TINHTHANH = default(int);
					}
					this.SendPropertyChanged("TINHTHANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.QUANHUYEN = this;
		}
		
		private void detach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.QUANHUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHINH")]
	public partial class LOAIHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIHINH;
		
		private string _TEN;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<System.DateTime> _NGAYSUA;
		
		private System.Nullable<int> _NGUOITAO;
		
		private System.Nullable<int> _NGUOISUA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private EntitySet<BANGGIADAT> _BANGGIADATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIHINHChanging(int value);
    partial void OnID_LOAIHINHChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnNGAYSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUAChanged();
    partial void OnNGUOITAOChanging(System.Nullable<int> value);
    partial void OnNGUOITAOChanged();
    partial void OnNGUOISUAChanging(System.Nullable<int> value);
    partial void OnNGUOISUAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public LOAIHINH()
		{
			this._BANGGIADATs = new EntitySet<BANGGIADAT>(new Action<BANGGIADAT>(this.attach_BANGGIADATs), new Action<BANGGIADAT>(this.detach_BANGGIADATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIHINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAIHINH
		{
			get
			{
				return this._ID_LOAIHINH;
			}
			set
			{
				if ((this._ID_LOAIHINH != value))
				{
					this.OnID_LOAIHINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIHINH = value;
					this.SendPropertyChanged("ID_LOAIHINH");
					this.OnID_LOAIHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(250)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSUA
		{
			get
			{
				return this._NGAYSUA;
			}
			set
			{
				if ((this._NGAYSUA != value))
				{
					this.OnNGAYSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUA = value;
					this.SendPropertyChanged("NGAYSUA");
					this.OnNGAYSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAO", DbType="Int")]
		public System.Nullable<int> NGUOITAO
		{
			get
			{
				return this._NGUOITAO;
			}
			set
			{
				if ((this._NGUOITAO != value))
				{
					this.OnNGUOITAOChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAO = value;
					this.SendPropertyChanged("NGUOITAO");
					this.OnNGUOITAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOISUA", DbType="Int")]
		public System.Nullable<int> NGUOISUA
		{
			get
			{
				return this._NGUOISUA;
			}
			set
			{
				if ((this._NGUOISUA != value))
				{
					this.OnNGUOISUAChanging(value);
					this.SendPropertyChanging();
					this._NGUOISUA = value;
					this.SendPropertyChanged("NGUOISUA");
					this.OnNGUOISUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINH_BANGGIADAT", Storage="_BANGGIADATs", ThisKey="ID_LOAIHINH", OtherKey="ID_LOAIHINH")]
		public EntitySet<BANGGIADAT> BANGGIADATs
		{
			get
			{
				return this._BANGGIADATs;
			}
			set
			{
				this._BANGGIADATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINH = this;
		}
		
		private void detach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETLOAI")]
	public partial class CHITIETLOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CHITIETLOAI;
		
		private string _TEN;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<System.DateTime> _NGAYSUA;
		
		private System.Nullable<int> _NGUOITAO;
		
		private System.Nullable<int> _NGUOISUA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private int _ID_LOAITAISAN;
		
		private EntitySet<BANGGIADAT> _BANGGIADATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CHITIETLOAIChanging(int value);
    partial void OnID_CHITIETLOAIChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnNGAYSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUAChanged();
    partial void OnNGUOITAOChanging(System.Nullable<int> value);
    partial void OnNGUOITAOChanged();
    partial void OnNGUOISUAChanging(System.Nullable<int> value);
    partial void OnNGUOISUAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnID_LOAITAISANChanging(int value);
    partial void OnID_LOAITAISANChanged();
    #endregion
		
		public CHITIETLOAI()
		{
			this._BANGGIADATs = new EntitySet<BANGGIADAT>(new Action<BANGGIADAT>(this.attach_BANGGIADATs), new Action<BANGGIADAT>(this.detach_BANGGIADATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHITIETLOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CHITIETLOAI
		{
			get
			{
				return this._ID_CHITIETLOAI;
			}
			set
			{
				if ((this._ID_CHITIETLOAI != value))
				{
					this.OnID_CHITIETLOAIChanging(value);
					this.SendPropertyChanging();
					this._ID_CHITIETLOAI = value;
					this.SendPropertyChanged("ID_CHITIETLOAI");
					this.OnID_CHITIETLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(250)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSUA
		{
			get
			{
				return this._NGAYSUA;
			}
			set
			{
				if ((this._NGAYSUA != value))
				{
					this.OnNGAYSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUA = value;
					this.SendPropertyChanged("NGAYSUA");
					this.OnNGAYSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAO", DbType="Int")]
		public System.Nullable<int> NGUOITAO
		{
			get
			{
				return this._NGUOITAO;
			}
			set
			{
				if ((this._NGUOITAO != value))
				{
					this.OnNGUOITAOChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAO = value;
					this.SendPropertyChanged("NGUOITAO");
					this.OnNGUOITAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOISUA", DbType="Int")]
		public System.Nullable<int> NGUOISUA
		{
			get
			{
				return this._NGUOISUA;
			}
			set
			{
				if ((this._NGUOISUA != value))
				{
					this.OnNGUOISUAChanging(value);
					this.SendPropertyChanging();
					this._NGUOISUA = value;
					this.SendPropertyChanged("NGUOISUA");
					this.OnNGUOISUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAITAISAN", DbType="Int NOT NULL")]
		public int ID_LOAITAISAN
		{
			get
			{
				return this._ID_LOAITAISAN;
			}
			set
			{
				if ((this._ID_LOAITAISAN != value))
				{
					this.OnID_LOAITAISANChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAITAISAN = value;
					this.SendPropertyChanged("ID_LOAITAISAN");
					this.OnID_LOAITAISANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETLOAI_BANGGIADAT", Storage="_BANGGIADATs", ThisKey="ID_CHITIETLOAI", OtherKey="ID_CHITIETLOAI")]
		public EntitySet<BANGGIADAT> BANGGIADATs
		{
			get
			{
				return this._BANGGIADATs;
			}
			set
			{
				this._BANGGIADATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETLOAI = this;
		}
		
		private void detach_BANGGIADATs(BANGGIADAT entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETLOAI = null;
		}
	}
}
#pragma warning restore 1591
